name: build-with-c

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: freebsd-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: make install
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
